attackdown/attackdown/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('', views.home),
    path('index/', views.index),
    path('produto/', include('produto.urls')),
    path('cliente/', include('cliente.urls')),
    path('carrinho/', include('carrinho.urls')),
    path('pedido/', include('pedido.urls')),
]

attackdown/pedido/urls.py
from django.urls import path

from pedido.models import Pedido
from .views import PedidoCreateView
from . import views

app_name = "pedidos"
urlpatterns = [
    path("criar/", PedidoCreateView.as_view(), name="criar"),
    path("lista/", views.lista_pedidos, name="lista"),
    path("detalhar/<str:id_pedido>/", views.detalha_pedido, name="terminar"),
    path("finaliza/<str:id_pedido>/", views.finaliza_pedido, name="finaliza"),
    #path('editar/<str:id_produto>/', views.editar_produto, name="editar-produto")
]

attackdown/pedido/models.py
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from model_utils.models import TimeStampedModel

from cliente.models import Cliente
from produto.models import Produto


class Pedido(TimeStampedModel):
    cnpj = models.ForeignKey(Cliente, on_delete=models.CASCADE, default=None)
    status = models.BooleanField(default=False)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return f"Pedido{self.id}"


class Item(models.Model):
    pedido = models.ForeignKey(Pedido, related_name="items", on_delete=models.CASCADE)
    produto = models.ForeignKey(
        Produto, related_name="order_items", on_delete=models.CASCADE
    )
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    quantidade = models.PositiveIntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(settings.CARRINHO_ITEM_MAX_QUANTIDADE),
        ]
    )

    def __str__(self):
        return str(self.id)

attackdown/pedido/forms.py
from django.db.models import fields
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Fieldset, Layout, Submit
from django import forms

from .models import Pedido
from pedido import models


class PedidoCreateForm(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = [
            "cnpj",
            "status",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.form_action = "."
        self.helper.add_input(
            Submit(
                "submit",
                "Finalizar compra",
                css_class="btn btn-success btn-lg btn-block",
            )
        )
        self.helper.layout = Layout(
            Fieldset(
                "",
                "cnpj",
                "status",
                css_class="border-bottom mb-3",
            )
        )

class FinalizaPedidoForm(forms.ModelForm):
    class Meta:
        model = models.Pedido
        fields = ['status']
        

attackdown/pedido/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView
from carrinho import forms
from django.contrib.auth.decorators import login_required

from carrinho.carrinho import Carrinho
import produto
from produto.models import Produto

from .forms import PedidoCreateForm, FinalizaPedidoForm
from .models import Item, Pedido


class PedidoCreateView(CreateView):
    model = Pedido
    form_class = PedidoCreateForm

    def form_valid(self, form):
        carrinho = Carrinho(self.request)
        if carrinho:
            pedido = form.save()
            for item in carrinho:
                Item.objects.create(
                    pedido=pedido,
                    produto=item["produto"],
                    preco=item["preco"],
                    quantidade=item["quantidade"],
                )
            carrinho.clear()
            return render(self.request, "pedido/pedido_created.html", {"pedido": pedido})
        return HttpResponseRedirect(reverse("pages:home"))

    """ def lista_pedidos(request):
        queryset = Pedido.objects.all()
        context = {
            'pedidos':queryset
        }
        return render(request, 'pedido/pedidos.html', context) """

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["carrinho"] = Carrinho(self.request)
        return context

@login_required(login_url='/accounts/login')
def lista_pedidos(request):
        queryset = Pedido.objects.all().order_by('status', 'created')
        context = {
            'pedidos':queryset
        }
        print(queryset)
        return render(request, 'pedido/pedidos.html', context)

def preco_total(preco, quantidade):
    return preco * quantidade

def preco_final(precos):
    preco_final = 0
    for preco in precos:
        preco_final += preco

    return preco_final

@login_required(login_url='/accounts/login')
def detalha_pedido(request, id_pedido):
    nomes = []
    precos = []
    pedido = get_object_or_404(Pedido, id=id_pedido)
    itens = Item.objects.filter(pedido_id=id_pedido)
    for item in itens:
        produto_id = item.produto_id
        nomes.append(Produto.objects.get(produto_id=produto_id))

    for item in itens:
        precos.append(preco_total(item.preco, item.quantidade))

    for nome in nomes:
        print(nome.nome)
    preco_pedido = preco_final(precos)

    context = {
        'pedido':pedido,
        'itens':itens,
        'nomes':nomes,
        'precos':precos,
        'preco_final':preco_pedido,
    }
    return render(request, 'pedido/finalizar_pedido.html', context)

@login_required(login_url='/accounts/login')
def finaliza_pedido(request, id_pedido):
    pedido = get_object_or_404(Pedido, id=id_pedido)
    if request.POST:
        form = FinalizaPedidoForm(request.POST, instance=pedido)
        if form.is_valid():
            pedido = form.save(commit=False)
            pedido.status = True
            pedido.save()
            return redirect('/pedido/lista', {'form':form})

attackdown/templates/pedido/finalizar_pedido.html
{% extends 'base.html' %}
{% block titulo %}Terminar pedido{% endblock titulo %}

{% block conteudo %}
<div style="width: 100%; height: 100%; align-content: center;">
    <div style="width: 50%; margin-right: auto; margin-left: auto;">
        <table border=1 style="display: inline-block; border-right: none;">
            <tr >
                <th>Produto</th>
            </tr>
            {% for nome in nomes %}
            <tr>
                <th>{{nome.nome}}</th>
            </tr>
            {% endfor %}
        </table>
        <table border=1 style="display: inline-block; border-right: none; border-left: none; padding-left: -20px;">
            <tr>
                <th>Quantidade</th>
                <th>Preço/unidade</th>
            </tr>
            {% for item in itens %}
            <tr>
                <th>{{item.quantidade}}</th>
                <th>{{item.preco}}</th>
            </tr>
            {% endfor %}
        </table>
        <table border=1 style="display: inline-block; border-left: none;">
            <tr >
                <th>Preço total</th>
            </tr>
            {% for preco in precos %}
            <tr>
                <th>{{preco}}</th>
            </tr>
            {% endfor %}
        </table><br><br>
        <b>PREÇO TOTAL = {{preco_final}}</b>
        {% if not pedido.status %}
        <form action="{% url 'pedidos:finaliza' pedido.id %}" method="post">
            {% csrf_token %}
            {{form.status}}
            <input type="submit" class="btn btn-primary" value="Terminar pedido">
        </form>
        {% endif %}
    </div>
</div>

{% endblock conteudo %}

attackdown/templates/pedido/pedido_created.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="refresh" name="viewport" content="5; URL='http://127.0.0.1:8000/pedido/lista/'">
    <title>Document</title>
</head>
<body>
</body>
</html>

attackdown/templates/pedido/pedido_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block titulo %}Checkout{% endblock titulo %}

{% block conteudo %}

<div class="container my-3">
    <h1 class="font-weight-bold">Checkout</h1>
    {% if carrinho %}
    <div class="row">
        <div class="col-lg-6">
            {% crispy form %}
        </div>
        <div class="col-lg-6">
            <div class="card border-0 bg-light p-4">
                <h4>Resumo do Pedido</h4>
                <ul class="list-group list-group-flush">
                    {% for item in carrinho %}
                    <li class="list-group-item bg-light">
                        {{ item.quantidade }}x {{ item.produto.nome }}
                        <span class="float-right">R$ {{ item.preco_total }}</span>
                    </li>
                    {% endfor %}
                    <li class="font-weight-bold list-group-item bg-light">Total
                        <span class="float-right">R$ {{ carrinho.get_preco_total }}</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    {% else %}
    <p>Seu carrinho está vazio.</p>
    {% endif %}
</div>

{% endblock conteudo %}

<!-- {% block script %}
<script src="https://unpkg.com/imask@6.0.7/dist/imask.js"></script>
<script src="{% static 'js/order-form.js' %}"></script>
{% endblock script %} -->

attackdown/templates/pedido/pedidos.html
{% extends "base.html" %}
{% block titulo %}Pedidos{% endblock titulo %}
{% block conteudo %}
<!-- {% block titulobody %}Pedidos{%endblock titulobody %} -->
    <table border=1 style="width: 100%;">
        <tr style="color: #ff0000;">
            <th>Código</th>
            <th>CNPJ Comprador</th>
            <th>Status</th>
            <th>Data</th>
            <th></th>
        </tr>
        {% for pedido in pedidos %}
        <tr {% if pedido.status %} style="color: grey;"{% endif %}>
            <th>{{pedido.id}}</th>
            <th>{{pedido.cnpj_id}}</th>
            <th>{% if pedido.status %}Pedido finalizado{% elif not pedido.status %}Pedido a finalizar{% endif %}</th>
            <th>{{pedido.created}}</th>
            <th><a href="{% url 'pedidos:terminar' pedido.id %}"><button class="btn btn-default">Detalhes</button></a></th>
        </tr>
        {% endfor %}
    </table><br>
{% endblock conteudo %}