attackdown/attackdown/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('', views.home),
    path('index/', views.index),
    path('produto/', include('produto.urls')),
    path('cliente/', include('cliente.urls')),
    path('carrinho/', include('carrinho.urls')),
    path('pedido/', include('pedido.urls')),
]

attackdown/carrinho/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.detalha_carrinho, name="detalhado"),
    path("add/<int:id_produto>/", views.add_carrinho, name="add-carrinho"),
    path("remove/<int:id_produto>/", views.remove_carrinho, name="remove-carrinho"),
]

attackdown/pedido/urls.py
from django.urls import path

from pedido.models import Pedido
from .views import PedidoCreateView
from . import views

app_name = "pedidos"
urlpatterns = [
    path("criar/", PedidoCreateView.as_view(), name="criar"),
    path("lista/", views.lista_pedidos, name="lista"),
    path("detalhar/<str:id_pedido>/", views.detalha_pedido, name="terminar"),
    path("finaliza/<str:id_pedido>/", views.finaliza_pedido, name="finaliza"),
    #path('editar/<str:id_produto>/', views.editar_produto, name="editar-produto")
]

attackdown/carrinho/models.py
from django.db import models

# Create your models here.

attackdown/carrinho/forms.py
from django import forms
from django.conf import settings

PRODUTO_QUANTIDADE_ESCOLHAS = [
    (i, str(i)) for i in range(1, settings.CARRINHO_ITEM_MAX_QUANTIDADE + 1)
]

class CarrinhoAddProdutoForm(forms.Form):
    quantidade = forms.TypedChoiceField(choices=PRODUTO_QUANTIDADE_ESCOLHAS, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

attackdown/carrinho/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.translation import override
from django.views.decorators.http import require_POST
from produto.models import Produto
from django.contrib.auth.decorators import login_required

from .carrinho import Carrinho
from .forms import CarrinhoAddProdutoForm

# Create your views here.
@login_required(login_url='/accounts/login')
def add_carrinho(request, id_produto):
    carrinho = Carrinho(request)
    produto = get_object_or_404(Produto, produto_id=id_produto)

    form = CarrinhoAddProdutoForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        carrinho.add(
            produto = produto,
            quantidade = cd["quantidade"],
            override_quantidade = cd["override"],
        )
    
    return redirect("/carrinho")

@login_required(login_url='/accounts/login')
def detalha_carrinho(request):
    carrinho = Carrinho(request)
    return render(request, "carrinho\carrinho_detalhado.html", {"carrinho":carrinho})

@login_required(login_url='/accounts/login')
@require_POST
def remove_carrinho(request, id_produto):
    carrinho = Carrinho(request)
    produto = get_object_or_404(Produto, produto_id=id_produto)
    carrinho.remove(produto)
    
    return redirect("/carrinho")

attackdown/templates/carrinho/carrinho_detalhado.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block titulo %}Carrinho{% endblock titulo %}

{% block titulobody %}Carrinho{%endblock titulobody %}

{% block conteudo %}
<table border=1 style="width: 100%;">
    <tr style="color: red;">
        <th>Produto</th>
        <th>Quantidade</th>
        <th>Preço unitário</th>
        <th>Preço total</th>
        <th></th>
    </tr>
    {% for item in carrinho %}
    {% with produto=item.produto %}
    <tr {% if produto.quantidade == 0 %} style="color: grey;"{% endif %}>
        <th>{{ produto.nome }}</th>
        <th>
            <form action="{% url 'add-carrinho' produto.produto_id %}" method="post">
                {% csrf_token %}
                {% render_field item.update_quantidade_form.quantidade class+="form-control" %}
                <input type="submit" value="Atualizar">
                {{ item.update_quantidade_form.override }}
            </form>
        </th>
        <th>{{ item.preco }}</th>
        <th>{{ item.preco_total }}</th>
        <th>
            <form action="{% url 'remove-carrinho' produto.produto_id %}" method="post">
                {% csrf_token %}
                <input class="btn btn-danger" type="submit" value="Remover">
            </form>
        </th>
    </tr>
    {% endwith %}
    {% endfor %}
</table>
<br>
<p><b>preço final: {{ carrinho.get_preco_total }}</b></p>
<br>
<div>
    <a href="/produto/lista"><button class="btn btn-primary">Voltar aos produtos</button></a>
    <a href="{% url 'pedidos:criar' %}"><button class="btn btn-success">Finalizar compra</button></a>
</div>
{% endblock conteudo %}